name: 'Setup Node environment'
author: 'Exlint'
description: 'Installing NodeJS, package manager, setting a cache and install dependencies'

inputs:
    should-cache:
        description: 'Whether caching is enabled'
        required: false
        default: 'true'
    node-version:
        description: 'Version of NodeJS to use'
        required: false
        default: latest
    package-manager:
        description: 'Which package manager should be used'
        required: false
        default: npm
    package-manager-version:
        description: 'Version of package-manager to use'
        required: false
        default: latest
    sub-modules:
        description: >
            Whether to checkout submodules: `true` to checkout submodules or `recursive` to
            recursively checkout submodules.
            When the `ssh-key` input is not provided, SSH URLs beginning with `git@github.com:` are
            converted to HTTPS.
        required: false
        default: 'false'

runs:
    using: 'composite'
    steps:
        - name: Check package manager
          if: inputs.package-manager != 'npm' && inputs.package-manager != 'yarn' && inputs.package-manager != 'pnpm'
          uses: actions/github-script@v7
          with:
              script: |
                  core.setFailed('Package manager must be either "npm", "yarn" or "pnpm"')

        - name: Checkout
          uses: actions/checkout@v3
          with:
              submodules: ${{ inputs.sub-modules }}

        - name: Install pnpm
          if: inputs.package-manager == 'pnpm'
          uses: pnpm/action-setup@v2
          with:
              version: ${{ inputs.package-manager-version }}

        - name: Setup Node.js
          if: ${{ inputs.should-cache == 'false' }}
          uses: actions/setup-node@v4
          with:
              node-version: ${{ inputs.node-version }}

        - name: Setup Node.js
          if: ${{ inputs.should-cache == 'true' }}
          uses: actions/setup-node@v4
          with:
              node-version: ${{ inputs.node-version }}
              cache: ${{ inputs.package-manager }}

        - name: Install npm
          if: inputs.package-manager == 'npm'
          run: npm i -g npm@${{ inputs.package-manager-version }}
          shell: bash

        - name: Install yarn
          if: inputs.package-manager == 'yarn'
          run: yarn set version ${{ inputs.package-manager-version }}
          shell: bash

        - name: Installing dependencies
          if: inputs.package-manager == 'npm'
          run: npm ci
          shell: bash

        - name: Installing dependencies
          if: inputs.package-manager == 'yarn'
          run: yarn install --immutable --immutable-cache --check-cache
          shell: bash

        - name: Installing dependencies
          if: inputs.package-manager == 'pnpm'
          run: pnpm i --frozen-lockfile --prefer-offline
          shell: bash
