name: Integration

on:
    pull_request:
        branches: [main]

jobs:
    test_pull_request:
        name: Testing & Checking the code
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node environment
              uses: ./
              with:
                  node-version: 18.11.0
                  pnpm-version: 7.14.0

            - name: Check unused dependencies
              run: pnpm depcheck

            - name: Check Typescript
              run: pnpm type-check

            - name: Check Prettier
              run: pnpm prettier
